//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationInMVC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int adminId { get; set; }
        public Nullable<int> contactId { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual contactU contactU { get; set; }
    }
}
