//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDOperationInMVC1
{
    using System;
    using System.Collections.Generic;
    
    public partial class complain
    {
        public int complainId { get; set; }
        public Nullable<int> studentId { get; set; }
        public string complain1 { get; set; }
    
        public virtual student student { get; set; }
    }
}
