//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperationInMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo_Tab
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string Adress { get; set; }
        public Nullable<double> Age { get; set; }
        public string Contact { get; set; }
    }
}
